# Explanations for each linter rule and their defaults can be found here:
# https://rubocop.readthedocs.io/en/latest/cops_style/

AllCops:
  TargetRubyVersion: 2.4

  # Ignore database migrations
  Exclude:
  - db/**

# The default line ending is based on your OS.
# If you are using LF on windows you'll need this rule.
#
# Layout/EndOfLine:
#   EnforcedStyle: lf

# Once Ruby makes immutable strings the default, this can be removed.
Style/FrozenStringLiteralComment:
  Enabled: false

# This is just a bad rule. Prefer double quoted strings.
StringLiterals:
  Enabled: false

# Prefer [:a, :b, :c] over %i(a b c)
# Ruby's % operators are too obscure to require this as a rule.
Style/SymbolArray:
  Enabled: false

# Requiring every class to have a comment is over-bearing.
# Unmaintained and/or bad documentation is worse than none at all.
Style/Documentation:
  Enabled: false