# First Travis CLI file for building Carpe
language: ruby
cache: bundler # Cache the bundler. Makes builds run faster, automatically reruns build when bundler changes
rvm:
  - 2.4.2
script:
  - bundle exec rails test
  - npm install
  - npm run teaspoon