# First Travis CLI file for building Carpe
language: ruby
cache: bundler # Cache the bundler. Makes builds run faster, automatically reruns build when bundler changes
rvm:
  - 2.4.2
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless
script:
  - bundle exec rails test
  - bundle exec teaspoon