# First Travis CLI file for building Carpe
language: ruby
cache: bundler # Cache the bundler. Makes builds run faster, automatically reruns build when bundler changes
rvm:
  - 2.3.0
script:
  - gem install bundler --pre
  - bundle exec rails
  - bundle exec rails teaspoon

before_install:
  - gem update bundler --pre
