# First Travis CLI file for building Carpe
language: ruby
cache: bundler # Cache the bundler. Makes builds run faster, automatically reruns build when bundler changes
rvm:
  - 2.4.2

# Handles installing anything needed for scripts
before_script:
  - npm install -g eslint # Install ESLint

# All tests and linting
script:
  - bundle exec rails test
  - bundle exec rake teaspoon
  - eslint app/assets/javascripts spec/javascripts # Run ESLint on JS code & Teaspoon tests (copied from package.json)
