#development:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: db_name_here
#  pool: 5
#  username: root
#  password:
#  host: localhost

default: &default
  adapter: mysql2
  encoding: utf8

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

#Make our test database use a copy of dev one (made 6/17/2016 11:16 PM CST) I guess?
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000  

production:
  adapter: mysql2
  <<: *default
  database: carpe_main
  #database: ruby-getting-started_production  
  username: viktor
  password: <%= ENV['RUBY-GETTING-STARTED_DATABASE_PASSWORD'] %>
